@url = "http://localhost:5000/"

GET http://localhost:5000/Flight HTTP/1.1

###

POST http://localhost:5000/Flight HTTP/1.1
Content-Type: application/json

{
    "title": "flight to canada",
    "time": "1pm",
    "price": "26000",
    "date": "26-06-2022"
}

###
GET http://localhost:5000/Flight HTTP/1.1

###
PUT https://localhost:5000/Flight HTTP/1.1
Content-Type: application/json

{
    "title": "flight to SA",
    "time": "3pm",
    "price": "29000",
    "date": "26-06-2022"
}
